name: CI/CD Pipeline Backend App

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Logging
              run: echo "Deployed!!!!"
